### ISSUE TITLE
cannot import operations from compas.datastructures.mesh

### ISSUE THREAD

**Issue by philianeles** [compas-dev/compas_fab#121]
cannot import operations from compas.datastructures.mesh
probably compas_fab version compatibility issue

1. Rhino 6, Grasshopper
2. See the image
3. See the image
4. cannot import operations from compas.datastructures.mesh

![image](https://user-images.githubusercontent.com/11179066/74938726-dccd8600-53ee-11ea-9cee-8b5184875b7f.png)

 - Windows 10
 - Python 3.7
 - conda

**Comment by philianeles** [comment]
It looks like the problem is not there when the compas_fab=0.10.2 instead of compas_fab=0.10.2-c9793b32 (see the image)
![image](https://user-images.githubusercontent.com/11179066/74946991-6fbfed80-53fa-11ea-8f08-c542833ab33c.png)

**Comment by brgcode** [comment]
it would make sense this is somehow related to `compas_fab` because i have checked release 0.13.3 and everything should be ok with the imports there...

**Comment by gonzalocasas** [comment]
I cannot reproduce the problem. I tested the exact same revisions mentioned in the issue, but it worked out fine. The only explanation I can think of is that maybe you had Rhino open and another version of COMPAS was already loaded in memory, when you updated to a different checkout the old version was still in memory and then the imports didn't match.

Since it seems to work for you, and I cannot reproduce, I will go ahead and close, but if you see this again, please re-open or open a new one.
