### ISSUE TITLE
Preparations for workshop TU Munich 

### ISSUE THREAD

**Issue by gonzalocasas** [compas-dev/compas_fab#127]
- [ ] https://github.com/gramaziokohler/workshop_munich_2020
- [ ] Slides
- [ ] Prepare UR10e control computer
- [ ] Presentation material for Assembly data structures

**Comment by tetov** [comment]
Prepare UR10e control computer:
https://github.com/tetov/ros-ur-controller-rpi

Current status: Kernel compiles fine but need to test. Ansible playbook mostly written (but not commited).

If you already know what ROS packages you'd like that would be helpful to know. Otherwise I'll research what's needed for UR control and MoveIt.
