### ISSUE TITLE
Pluggable backend features: define API

### ISSUE THREAD

**Issue by beverlylytle** [compas-dev/compas_fab#253]
As a first step in the direction of switching to `compas.plugin`-based backend features, we should first define the API that we want to have from a user perspective.

**Comment by gonzalocasas** [comment]
Notes of the meeting today:

* Each backend feature is a pluggable
* Change `planner_backend` argument in `RosClient` to accept a type directly, instead of just a string mapped to a type
* Add to documentation: how to write your own custom planner/solver
* Consider moving whole planning scene state to our side (as a list of updates) and then flush it to the backend right before any calculation (if it changed)
* Use `client.planner` as main mechanism to switch backend feature sets
* Use `client.planner.inverse_kinematics = my_inverse_kinematics` as main mechanism to switch individual backend features
* `PlannerInterface` becomes a pluggable, and then, e.g. `MoveItPlanner` is automatically discovered
* We could try to integrate Tesseract, or instead of that, try to do the same with multiple `ExecutorInterface` implementations (`MoveItExecutor` {follow/execute}, `CompasRRCExecutor`, etc)

I believe this is closed, and we will create follow-ups to start implementing these changes.
