### ISSUE TITLE
Path planning via MoveIt: collision matrix

### ISSUE THREAD

**Issue by romanarust** [compas-dev/compas_fab#32]
The collision calculation between the `CollisionObject` (scene geometry) and an `AttachedCollisionObject` requires to update the allowed collision matrix, for example by calling the [ApplyPlanningScene service](http://docs.ros.org/melodic/api/moveit_msgs/html/srv/ApplyPlanningScene.html). 
TODO: add necessary messages to ros backend and automatically apply after calling `CollisionObject` or `AttachedCollisionObject`.

**Comment by yijiangh** [comment]
Just curious, do we have any plan on fetching the planning scene back to the compas_fab side and **visualize** it after we send out the service, to check what are the current collision objects and attached objects? 

I think it is quite useful for the users to immediately see what's going on in the scene, instead of just facing this ROS blackbox running in the backend. In ROS, the planning scene can be displayed in real-time if Rviz is running, and I found it very useful in my code development.

**Comment by romanarust** [comment]
Closing this one, as updating `the CollisionObject (scene geometry) and an AttachedCollisionObject requires to update the allowed collision matrix` is not necessary.
The comment below belongs to #46 and #53
